version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Build JAR
          command: |
            ./gradlew build
            cp build/libs/*.jar app.jar
      - run:
          name: Build Docker image
          command: |
            docker build -t gabriel123125/projectv2 .
  deploy:
    docker:
      - image: gabriel123125/projectv2
    steps:
      - checkout
      - run:
          name: Deploy to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push gabriel123125/projectv2
