apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectv2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projectv2
  template:
    metadata:
      labels:
        app: projectv2
    spec:
      containers:
        - name: projectv2
          image: gabriel123125/projectv2
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: projectv2
spec:
  type: NodePort
  selector:
    app: projectv2
  ports:
    - protocol: TCP
      port: 8080