version: 2.1

orbs:
  java: circleci/openjdk@1.2.2
  docker: circleci/docker@1.3.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: ./mvnw clean install -DskipTests=true
      - run: docker build -t Gabriel123125/projectv2:latest .
      - run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run: docker push Gabriel123125/projectv2:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
